### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Renfield1897** [deadhead420/fetchmirrors#6]
HI

There seems to be a typo is the fetchmirrors.sh script, as it is failing when you try and use it for https servers, but works for all servers and each of the country codes

I am a total code newbie, so I might be wrong....

The code is 

2)	# Set query to all https mirrors
					country="All HTTPS"
					query+="https://www.archlinux.org/mirrorlist/all/https"
					break

And should read

2)	# Set query to all https mirrors
					country="All HTTPS"
					query="https://www.archlinux.org/mirrorlist/all/https"
					break

Thanks
Ren

**Comment by deadhead420** [comment]
Fixed. Thank you for letting me know. Turns out the problem was the link was missing the trailing "/"

It should be: https://www.archlinux.org/mirrorlist/all/https/
not: https://www.archlinux.org/mirrorlist/all/https

I did also remove the "+" from query as its not really needed but wasn't causing the issue. Thanks again for letting me know. Updated on github and the aur package.
